### ISSUE TITLE
getClosedPnl

### ISSUE THREAD

**Issue by sergiojm** [sieblyio/bybit-api#100]
Using getClosedPnl it throws an 404.

Looking at the code on linear-client its set as:

return this.requestWrapper.get('private/linear/tpsl/switch-mode', params);

changing to 

return this.requestWrapper.get('/private/linear/trade/closed-pnl/list', params);

It works.

Its a bug or I am getting something wrong?

**Comment by tiagosiebler** [comment]
Good catch! 

Seems a mistake found its way into that particular method, I've corrected it and it should be working as of v2.0.6. Thanks!
