### ISSUE TITLE
No wallet methods?

### ISSUE THREAD

**Issue by danajeremy** [sieblyio/bybit-api#102]
Hello!

Thanks a lot for the package, it's really useful!

I was wondering, there is no method to fetch the wallet balance (nor any methods related to the wallet), is that on purpose?

**Comment by tiagosiebler** [comment]
Hello, glad to hear you're finding it useful! The wallet methods are inherited from the "shared-endpoints", so you can call them directly from the inverse/linear/etc clients. You can see them here:
https://github.com/tiagosiebler/bybit-api/blob/master/src/shared-endpoints.ts#L85-L126

If you have ideas on making this more intuitive, I'd be open to improvements. Thanks!

**Comment by danajeremy** [comment]
Ah! Awesome, thanks a lot for that!
No real ideas but it would be good to write it in the readme! :)
