### ISSUE TITLE
Verify recv_window logic

### ISSUE THREAD

**Issue by tiagosiebler** [sieblyio/bybit-api#5]
> server_time - recv_window <= timestamp < server_time + 1000; server_time stands for Bybit server time, you can get it from Server Time endpoint

```
{
  "ret_code": 10002,
  "ret_msg": "invalid request, please check your timestamp and recv_window param. req_timestamp: 1595314750121 server_timestamp: 1595314742549 recv_window: 15000",
  "ext_code": "",
  "ext_info": "",
  "result": null,
  "time_now": "1595314742.549034",
  "message": "invalid request, please check your timestamp and recv_window param. req_timestamp: 1595314750121 server_timestamp: 1595314742549 recv_window: 15000"
}

```

**Comment by tiagosiebler** [comment]
No issues seen in a while, closing this

**Comment by doppelgunner** [comment]
Hi, I noticed this problem too. from time to time my bot experienced this kind of problem which causes error.
![image](https://user-images.githubusercontent.com/10264898/124197541-56a47200-db01-11eb-9cd4-6b43f8a6d2d6.png)

Please help I don't know how to fix this. I'm only using the API every 3 minutes to check positions and order short or long, and the websocket everytime the price changes. It's not like I'm requesting too much from my point of view.

**Comment by tiagosiebler** [comment]
> Hi, I noticed this problem too. from time to time my bot experienced this kind of problem which causes error.
> ![image](https://user-images.githubusercontent.com/10264898/124197541-56a47200-db01-11eb-9cd4-6b43f8a6d2d6.png)
> 
> Please help I don't know how to fix this. I'm only using the API every 3 minutes to check positions and order short or long, and the websocket everytime the price changes. It's not like I'm requesting too much from my point of view.

99% of the time this is related to either your machine's system time (it's out of sync), or network latency causing your requests to take too long to be processed by the server. With a recv_window of 5000 you have 5000 milliseconds before your request becomes invalid. If your request too longer than that to reach the server, it will reject it to protect you. Here's an explanation including how to handle it: https://bybit-exchange.github.io/docs/inverse/#t-authenticationparameters

In the log you can see your request timestamp and the server timestamp (when the server received and tried to process it):
1625171421202-1625171400007 = 21195. It took 21195ms, more than 4x your current recv window.

While the library tries to provide some handling out-of-sync time, there's not much it can do if the request took too long on your machine. Recommendations:
- verify your server time is in sync (e.g using `ntp` in unix environments)
- verify your server's network is not experiencing latency issues or use a server closer to bybit's services.
- lastly you could as a workaround increase your recv_window from 5000 to something higher but it puts you at risk of repeat attacks if your request is ever intercepted. 

The recv_window change is definitely a last resort, but if you want to try that at least as a workaround, you can set this via the `RestClientOptions` taken by any of the REST clients in this library:
https://github.com/tiagosiebler/bybit-api/blob/da8dbd57237c32dc0273a10f54f82005a5230954/src/util/requestUtils.ts#L3

**Comment by pinwhell** [comment]
i got the most likely causing the problem, the thing was, that the server expect a 64 bit time stamp, thats why everytime is getting triggered, that its out of range of the window of time SIZOEF(MAXINT64) - SIZEOF(MAXINT32)  => Always Out of Range Time Stamp

**Comment by tiagosiebler** [comment]
> i got the most likely causing the problem, the thing was, that the server expect a 64 bit time stamp, thats why everytime is getting triggered, that its out of range of the window of time SIZOEF(MAXINT64) - SIZEOF(MAXINT32) => Always Out of Range Time Stamp

@pinwhell if you're seeing this on every request, you should sync your system clock with a time service. More info here:
https://github.com/tiagosiebler/awesome-crypto-examples/wiki/Timestamp-for-this-request-is-outside-of-the-recvWindow

**Comment by pinwhell** [comment]
I manage to solve it, and also relized that the unix size is neither the problem, the true problem was i was sending the time stamp in seconds insteads of milloseconds, miltipling it by 1000 ( Converting to Millis ) solved the problem

**Comment by tiagosiebler** [comment]
> I manage to solve it, and also relized that the unix size is neither the problem, the true problem was i was sending the time stamp in seconds insteads of milloseconds, miltipling it by 1000 ( Converting to Millis ) solved the problem

Glad you found the issue but you also shouldn't need to construct your own timestamps. This SDK handles timestamps automatically as part of the signing process when you call a method linked to a private endpoint.
