### ISSUE TITLE
error requestWrapper.js

### ISSUE THREAD

**Issue by jecombe** [sieblyio/bybit-api#73]
i'm using testnet, I run my program, after a moment i have this error:

> (node:11650) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'options' of undefined
>     at parseException (/home/ubuntu/bybit/node_modules/bybit-api/lib/util/requestWrapper.js:83:18)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> (node:11650) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 66984)

i create my object restClient like this: 

>  new RestClient(process.env.API_KEY, process.env.PRIVATE_KEY, IS_LIVE_NET, REST_OPTION);

Someone would have any idea ?

**Comment by tiagosiebler** [comment]
Hey @jecombe - I've pushed a fix to what caused this error. In reality this logic (parseException) was actually supposed to show you a deeper issue with your request. Perhaps your API credentials (or the IP binding) is incorrect, or something else went wrong (e.g can't reach bybit's servers). 

If you try again with the latest version (v1.3.2) it should show you the real error.

**Comment by tiagosiebler** [comment]
Confirmed closed in msg.
