### ISSUE TITLE
Data comes in twice from the websocket position

### ISSUE THREAD

**Issue by k3341095** [sieblyio/bybit-api#76]
Connect to webso and subscribe to the position
When you buy coins at the market price
The signal flies twice..
Is it originally like that? Or is it a bug?

I am using a testnet.

**Comment by tiagosiebler** [comment]
It's originally like that - I see it too sometimes. I think it's more common when multiple position events happen in a short amount of time. For example if you place a larger market order that sees many smaller partial fills, I think each fill triggers a position update. 

For position updates, this library just relays raw events coming from the websocket - you can follow it from here down to the ` this.emit('update', message)` call further down:
https://github.com/tiagosiebler/bybit-api/blob/master/src/websocket-client.ts#L239

**Comment by raifemre** [comment]
I am also having the same problem, to quick fix this; store id's of data and do not evaluate duplicate ones
