### ISSUE TITLE
Margin Switch

### ISSUE THREAD

**Issue by aren-nalbandyan** [sieblyio/bybit-api#95]
Please add feature for Switching margin mode (Cross, Isolated)
Testnet's API working perfect, but real API always returns 404

**Comment by tiagosiebler** [comment]
Thanks for pointing this out, were you referring to the inverse client? Seems I was missing these recently added endpoints for the inverse client. I've now added these, released in version 2.0.5 of this module: `npm i bybit-api@latest --save`. Let me know if that resolves it.

**Comment by aren-nalbandyan** [comment]
Thank you a lot. It works in testnet, but Bybit has problem with non-testnet endpoint :) it returns 404

**Comment by tiagosiebler** [comment]
Since it works in testnet it might just be that it isn't released yet...
